# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da72bf1139196c3332ef72137091732a42dd0dcc07eaad7444a9e57f152385d330ff11bbf1017010784495fa8c42de5391c3ae62b46a3ee5810fc17e9996d88e

test:
  secret_key_base: 61b67f53015c4b60c8d4acab4e989e50a6cf3c8de9d0043f34c25498907c73af7e3b413b20a8a2e8d5c73dc9d21aecf923a1a773cbe7d71289c8563723b19637

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
